spring.application.name=CommandeFournisseur

spring.datasource.url=jdbc:postgresql://localhost:5432/tricoldb
spring.datasource.username=postgres
spring.datasource.password=barca1230/

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
